services:
  php:
    build:
      context: .
    restart: always
    ports:
      # HTTP
      - target: 80
        published: ${HTTP_PORT:-80}
        protocol: tcp
      # HTTPS
      - target: 443
        published: ${HTTPS_PORT:-443}
        protocol: tcp
      # HTTP/3
      - target: 443
        published: ${HTTP3_PORT:-443}
        protocol: udp
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - database
  database:
    image: mysql:8
    platform: linux/amd64
    restart: on-failure
    ports:
      - 33060:3306
    volumes:
      - database_data:/var/lib/mysql:rw
    environment:
      MYSQL_DATABASE: xgp
      MYSQL_ROOT_PASSWORD: root

volumes:
  caddy_data:
  caddy_config:
  ###> symfony/mercure-bundle ###
  ###< symfony/mercure-bundle ###

  ###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###