apiVersion: v2
name: xgp-rebirth
description: Helm chart for the XGP Rebirth project

type: application
version: 0.1.0

appVersion: "0.1.0"

dependencies:
  - name: mysql
    repository: https://charts.bitnami.com/bitnami
    version: 12.2.2
    condition: mysql.enabled