apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "xgp-rebirth.fullname" . }}
  labels:
    app: {{ template "xgp-rebirth.name" . }}
    chart: {{ template "xgp-rebirth.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: {{ template "xgp-rebirth.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "xgp-rebirth.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          env:
            - name: SERVER_NAME
              value: ':80'
            - name: APP_ENV
              value: prod
            - name: DATABASE_URL
              # TODO: replace with secure variant
              value: "mysql://{{ .Values.mysql.auth }}:{{ .Values.mysql.auth.password }}@mysql:3306/{{  .Values.mysql.auth.database }}?serverVersion=9&charset=utf8mb4"
            - name: APP_SECRET
              value: {{ .Values.env.APP_SECRET }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}