apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "xgp-rebirth.fullname" . }}
  labels:
    app: {{ template "xgp-rebirth.name" . }}
    chart: {{ template "xgp-rebirth.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: {{ template "xgp-rebirth.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "xgp-rebirth.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          env:
            - name: SERVER_NAME
              value: ':80'
            - name: APP_ENV
              value: prod
            - name: DATABASE_USER
              value: {{ .Values.mysql.auth.username }}
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mysql.auth.existingSecret }}
                  key: mysql-password
            - name: APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.app }}
                  key: app-secret

            - name: DATABASE_URL
              value: mysql://$(DATABASE_USER):$(DATABASE_PASSWORD)@{{ .Values.mysql.host }}:3306/{{  .Values.mysql.auth.database }}?serverVersion=8'
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}